{
 "title": "Goque Queue Metrics",
 "tags": [
  "goque",
  "queue",
  "metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "rate_interval", "query": "10s,30s,1m,5m,10m" },
   {
    "name": "processor",
    "query": {
     "query": "label_values(goque_processed_tasks_total{service=\"$service\"},task_type)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(goque_processed_tasks_total,service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Common", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "New rate [q95]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "p95" ] } },
   "targets": [
    {
     "expr": "sum(increase(goque_processed_tasks_total{service=\"$service\", task_type=~\"$processor\", status=~\"new\"}[$rate_interval]))"
    }
   ]
  },
  {
   "title": "Success [q95]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "p95" ] } },
   "targets": [
    {
     "expr": "sum(increase(goque_processed_tasks_total{service=\"$service\", task_type=~\"$processor\", status=\"done\"}[$rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate [q95]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "p95" ] } },
   "targets": [
    {
     "expr": "sum(increase(goque_processed_tasks_total{service=\"$service\", task_type=~\"$processor\", status=~\"attempts_left|error\"}[$rate_interval]))"
    }
   ]
  },
  {
   "title": "Payload Decode Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(goque_payload_decode_errors_total{service=\"$service\", task_type=~\"$processor\"}[$rate_interval]))"
    }
   ]
  },
  {
   "title": "Processing Duration [q95]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (goque_task_processing_duration_seconds_bucket{service=\"$service\", task_type=~\"$processor\"}[$rate_interval]))"
    }
   ]
  },
  {
   "title": "Task Processing",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(increase(goque_processed_tasks_total{service=\"$service\", task_type=~\"$processor\"}[$rate_interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Task Processing Duration [q95]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, task_type) (goque_task_processing_duration_seconds_bucket{service=\"$service\", task_type=~\"$processor\"}[$rate_interval]))",
     "legendFormat": "{{task_type}}"
    }
   ]
  },
  { "title": "Processor: $processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "processor" },
  {
   "title": "State [q95]",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 17, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "p95" ] } },
   "targets": [
    {
     "expr": "sum(increase(goque_processed_tasks_total{service=\"$service\", task_type=~\"$processor\", status=\"new\"}[$rate_interval]))",
     "legendFormat": "new"
    },
    {
     "expr": "sum(increase(goque_processed_tasks_total{service=\"$service\", task_type=~\"$processor\", status=\"done\"}[$rate_interval]))",
     "legendFormat": "done"
    },
    {
     "expr": "sum(increase(goque_processed_tasks_total{service=\"$service\", task_type=~\"$processor\", status=~\"attempts_left|error\"}[$rate_interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Retry attempts [q95]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, task_type) (goque_task_retry_attempts_bucket{service=\"$service\", task_type=~\"$processor\"}[$rate_interval]))",
     "legendFormat": "Retry attempts"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (task_type) (goque_processors_workers_count{service=\"$service\", task_type=~\"$processor\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Processing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (task_type, status)(increase(goque_processed_tasks_total{service=\"$service\", task_type=~\"$processor\"}[$rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Task Processing Duration [q95)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, task_type) (goque_task_processing_duration_seconds_bucket{service=\"$service\", task_type=~\"$processor\"}[$rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Payload Size [q95]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, task_type)(goque_task_payload_size_bytes_bucket{service=\"$service\", task_type=~\"$processor\"}[$rate_interval]))",
     "legendFormat": "{{task_type}}"
    }
   ]
  },
  {
   "title": "Internal processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    {
     "title": "Internal process: $processor",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 277 },
     "repeat": "processor",
     "targets": [
      {
       "expr": "sum by (operation) (increase(goque_operations_total{service=\"$service\", task_type=~\"$processor\"}[$rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}