// Package worker contains the worker logic for generating tasks.
package worker

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"math/rand"
	"time"

	"github.com/google/uuid"
	"github.com/ruko1202/xlog"
	"github.com/ruko1202/xlog/xfield"

	"example/internal/config"
	"example/internal/models"

	"github.com/ruko1202/goque"
)

// TaskGenerator generates tasks based on the provided configuration.
type TaskGenerator struct {
	queueManager goque.TaskQueueManager
	cfg          config.TaskGeneratorConfig
	taskTypes    []models.TaskType
}

// NewTaskGenerator creates a new TaskGenerator instance.
func NewTaskGenerator(
	cfg config.TaskGeneratorConfig,
	queueManager goque.TaskQueueManager,
	taskTypes []models.TaskType,
) *TaskGenerator {
	return &TaskGenerator{
		cfg:          cfg,
		queueManager: queueManager,
		taskTypes:    taskTypes,
	}
}

// ProcessTask generates demo tasks when the periodic scheduler enqueues a generator task.
func (g *TaskGenerator) ProcessTask(ctx context.Context, _ *goque.Task) error {
	xlog.Info(ctx, "Processing task generator",
		xfield.Int("min_tasks", g.cfg.MinTasks),
		xfield.Int("max_tasks", g.cfg.MaxTasks),
	)

	return g.generateTasks(ctx)
}

func (g *TaskGenerator) generateTasks(ctx context.Context) error {
	numTasks := g.cfg.MinTasks
	if g.cfg.MaxTasks > g.cfg.MinTasks {
		numTasks += rand.Intn(g.cfg.MaxTasks - g.cfg.MinTasks + 1) //nolint:gosec
	}

	ctx, span := xlog.WithOperationSpan(ctx, "generateTasks",
		xfield.Int("count", numTasks),
	)
	defer span.End()

	var runErr error
	for _, taskType := range g.taskTypes {
		for i := 0; i < numTasks; i++ {
			task, err := generateTask(taskType)
			if err != nil {
				xlog.Error(ctx, "Failed to generate task",
					xfield.String("taskType", taskType),
					xfield.Error(err),
				)
				runErr = errors.Join(runErr, err)
				continue
			}

			err = g.queueManager.AddTaskToQueue(ctx, task)
			if err != nil {
				xlog.Error(ctx, "Failed to add generated task to queue",
					xfield.String("taskType", taskType),
					xfield.Error(err),
				)
				runErr = errors.Join(runErr, err)
			}
		}
	}

	return runErr
}

func generateTask(taskType models.TaskType) (*goque.Task, error) {
	if taskType == models.TaskTypeEmail {
		payload := &models.EmailPayload{
			To:      fmt.Sprintf("user%d@example.com", time.Now().UnixNano()),
			Subject: fmt.Sprintf("Test Email %d", time.Now().UnixNano()),
			Body:    "This is a test email generated by the task generator.",
		}
		return goque.NewTaskWithPayloadAndExternalID(taskType, payload, uuid.NewString())
	}

	payload, err := generatePayload(taskType)
	if err != nil {
		return nil, err
	}

	return goque.NewTaskWithExternalID(taskType, string(payload), uuid.NewString()), nil
}

func generatePayload(taskType models.TaskType) ([]byte, error) {
	switch taskType {
	case models.TaskTypeEmail:
		return nil, fmt.Errorf("unsupported task type for old flow: %s", taskType)

	case models.TaskTypeNotification:
		payload := models.NotificationPayload{
			UserID:  fmt.Sprintf("user-%d", time.Now().UnixNano()),
			Title:   fmt.Sprintf("Notification %d", time.Now().UnixNano()),
			Message: "This is a test notification generated by the task generator.",
		}
		return json.Marshal(payload)

	case models.TaskTypeReport:
		formats := []string{"pdf", "csv", "xlsx"}
		reportTypes := []string{"sales", "usage", "analytics"}
		payload := models.ReportPayload{
			ReportType: reportTypes[rand.Intn(len(reportTypes))], //nolint:gosec
			DateFrom:   time.Now().AddDate(0, 0, -30).Format("2006-01-02"),
			DateTo:     time.Now().Format("2006-01-02"),
			Format:     formats[rand.Intn(len(formats))], //nolint:gosec
		}
		return json.Marshal(payload)

	case models.TaskTypeWebhook:
		methods := []string{"POST", "PUT"}
		payload := models.WebhookPayload{
			URL:    fmt.Sprintf("https://api.example.com/webhook/%d", time.Now().UnixNano()),
			Method: methods[rand.Intn(len(methods))], //nolint:gosec
			Headers: map[string]string{
				"Content-Type":  "application/json",
				"Authorization": "Bearer token123",
			},
			Body: `{"event": "test", "timestamp": "` + time.Now().Format(time.RFC3339) + `"}`,
		}
		return json.Marshal(payload)

	default:
		return nil, fmt.Errorf("unknown task type: %s", taskType)
	}
}
