// Package worker contains the worker logic for generating tasks.
package worker

import (
	"context"
	"encoding/json"
	"fmt"
	"math/rand"
	"time"

	"github.com/google/uuid"
	"github.com/ruko1202/xlog"
	"github.com/ruko1202/xlog/xfield"

	"example/internal/config"
	"example/internal/models"

	"github.com/ruko1202/goque"
)

// TaskGenerator generates tasks based on the provided configuration.
type TaskGenerator struct {
	queueManager goque.TaskQueueManager
	cfg          config.TaskGeneratorConfig
	taskTypes    []models.TaskType
}

// NewTaskGenerator creates a new TaskGenerator instance.
func NewTaskGenerator(
	cfg config.TaskGeneratorConfig,
	queueManager goque.TaskQueueManager,
	taskTypes []models.TaskType,
) *TaskGenerator {
	return &TaskGenerator{
		cfg:          cfg,
		queueManager: queueManager,
		taskTypes:    taskTypes,
	}
}

// Run starts the task generator.
func (g *TaskGenerator) Run(ctx context.Context) {
	xlog.Info(ctx, "Starting task generator",
		xfield.Duration("interval", g.cfg.Interval),
		xfield.Int("min_tasks", g.cfg.MinTasks),
		xfield.Int("max_tasks", g.cfg.MaxTasks),
	)

	ticker := time.NewTicker(g.cfg.Interval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			xlog.Info(ctx, "Task generator stopped")
			return
		case <-ticker.C:
			g.generateTasks(ctx)
		}
	}
}

func (g *TaskGenerator) generateTasks(ctx context.Context) {
	numTasks := g.cfg.MinTasks + rand.Intn(g.cfg.MaxTasks-g.cfg.MinTasks+1) //nolint:gosec
	ctx, span := xlog.WithOperationSpan(ctx, "generateTasks",
		xfield.Int("count", numTasks),
	)
	defer span.End()

	for _, taskType := range g.taskTypes {
		for i := 0; i < numTasks; i++ {
			payload, err := generatePayload(taskType)
			if err != nil {
				xlog.Error(ctx, "Failed to generate payload",
					xfield.String("taskType", taskType),
					xfield.Error(err),
				)
				continue
			}

			g.queueManager.AsyncAddTaskToQueue(ctx, goque.NewTaskWithExternalID(
				taskType,
				string(payload),
				uuid.NewString(),
			))
		}
	}
}

func generatePayload(taskType models.TaskType) ([]byte, error) {
	switch taskType {
	case models.TaskTypeEmail:
		payload := models.EmailPayload{
			To:      fmt.Sprintf("user%d@example.com", time.Now().UnixNano()),
			Subject: fmt.Sprintf("Test Email %d", time.Now().UnixNano()),
			Body:    "This is a test email generated by the task generator.",
		}
		return json.Marshal(payload)

	case models.TaskTypeNotification:
		payload := models.NotificationPayload{
			UserID:  fmt.Sprintf("user-%d", time.Now().UnixNano()),
			Title:   fmt.Sprintf("Notification %d", time.Now().UnixNano()),
			Message: "This is a test notification generated by the task generator.",
		}
		return json.Marshal(payload)

	case models.TaskTypeReport:
		formats := []string{"pdf", "csv", "xlsx"}
		reportTypes := []string{"sales", "usage", "analytics"}
		payload := models.ReportPayload{
			ReportType: reportTypes[rand.Intn(len(reportTypes))], //nolint:gosec
			DateFrom:   time.Now().AddDate(0, 0, -30).Format("2006-01-02"),
			DateTo:     time.Now().Format("2006-01-02"),
			Format:     formats[rand.Intn(len(formats))], //nolint:gosec
		}
		return json.Marshal(payload)

	case models.TaskTypeWebhook:
		methods := []string{"POST", "PUT"}
		payload := models.WebhookPayload{
			URL:    fmt.Sprintf("https://api.example.com/webhook/%d", time.Now().UnixNano()),
			Method: methods[rand.Intn(len(methods))], //nolint:gosec
			Headers: map[string]string{
				"Content-Type":  "application/json",
				"Authorization": "Bearer token123",
			},
			Body: `{"event": "test", "timestamp": "` + time.Now().Format(time.RFC3339) + `"}`,
		}
		return json.Marshal(payload)

	default:
		return nil, fmt.Errorf("unknown task type: %s", taskType)
	}
}
